README.md
<details>
<summary>📦 Published PR as canary version: <code>0.0.5--canary.3.c4b5d5e.0</code></summary>
<br />
```bash
npm install @storybook/testing-react@0.0.5--canary.3.c4b5d5e.0
yarn add @storybook/testing-react@0.0.5--canary.3.c4b5d5e.0
```
</details>
=> docs: fix wrong import in instructions

package.json
It was still using the old url!
<details>
<summary>📦 Published PR as canary version: <code>0.0.8--canary.10.629757d.0</code></summary>
<br />
```bash
npm install @storybook/testing-react@0.0.8--canary.10.629757d.0
yarn add @storybook/testing-react@0.0.8--canary.10.629757d.0
```
</details>
=> chore: update package url

example/src/stories/Button.test.tsx, src/index.ts
issue: #13
<details>
<summary>📦 Published PR as canary version: <code>0.0.10--canary.14.4ab5831.0</code></summary>
<br />
```bash
npm install @storybook/testing-react@0.0.10--canary.14.4ab5831.0
yarn add @storybook/testing-react@0.0.10--canary.14.4ab5831.0
```
</details>
=> fix: support addons that use channel api

README.md, example/src/stories/Button.test.tsx, src/index.ts
issue: #17 
<details>
<summary>📦 Published PR as canary version: <code>0.0.11--canary.18.8c0df86.0</code></summary>
<br />
```bash
npm install @storybook/testing-react@0.0.11--canary.18.8c0df86.0
yarn add @storybook/testing-react@0.0.11--canary.18.8c0df86.0
```
</details>
=> fix: throw error on unsupported formats

package.json
<details>
<summary>📦 Published PR as canary version: <code>0.0.12--canary.21.ebe57b5.0</code></summary>
<br />
```bash
npm install @storybook/testing-react@0.0.12--canary.21.ebe57b5.0
yarn add @storybook/testing-react@0.0.12--canary.21.ebe57b5.0
```
</details>
=> fix: module field should point to a real file

package.json, src/types.ts
It appears the import path used for `StoryFnReactReturnType` no longer exists in `@storybook/react` from `6.2` and onwards.
This is causing a type error when used externally.
As this type is only `ReactElement<unknown>` I thought it would be better to inline this and avoid a deep import.
=> fix: Remove deep import StoryFnReactReturnType from @storybook/react

README.md, package.json, yarn.lock
In order to avoid conflicts between storybook versions, @storybook/testing-react should be reliant on user's storybook version instead.
<details>
<summary>📦 Published PR as canary version: <code>0.0.16--canary.23.aac7bcc.0</code></summary>
<br />
```bash
npm install @storybook/testing-react@0.0.16--canary.23.aac7bcc.0
yarn add @storybook/testing-react@0.0.16--canary.23.aac7bcc.0
```
</details>
=> fix: move storybook libs as peer deps

package.json
Fixes #25 
This uses a more liberal `>=` semver range for peer dependencies, to allow installations with pre-release versions of storybook (and react for that matter) with npm 7.  It's also just good practice to be as open as possible with peer dependencies, to avoid problems like reach-router has right now (https://github.com/reach/router/pull/432#issuecomment-734891630)
<details>
<summary>📦 Published PR as canary version: <code>0.0.17--canary.26.e11efee.0</code></summary>
<br />
```bash
npm install @storybook/testing-react@0.0.17--canary.26.e11efee.0
yarn add @storybook/testing-react@0.0.17--canary.26.e11efee.0
```
</details>
=> Widen peer dependency range to include prereleases

README.md
<details>
<summary>📦 Published PR as canary version: <code>0.0.18--canary.33.6e6a4b1.0</code></summary>
<br />
```bash
npm install @storybook/testing-react@0.0.18--canary.33.6e6a4b1.0
yarn add @storybook/testing-react@0.0.18--canary.33.6e6a4b1.0
```
</details>
=> Update TS information

README.md
- Replaced `returend` with `returned` Under Reusing story properties
=> (docs) README - Corrected a small typo

README.md, example/package.json, example/src/components/Button.stories.tsx, example/src/components/Button.test.tsx, example/src/internals.test.tsx, example/yarn.lock, package.json, src/index.ts, src/types.ts, src/utils.tsx, yarn.lock
- Bring back support to CSF3
Storybook released a [new version of CSF](https://storybook.js.org/blog/component-story-format-3-0/), where the story can also be an object. This is supported in @storybook/testing-react, but you have to match the requisites:
1 - Either your **story** has a `render` method or your **meta** contains a `component` property:
```js
// Example 1: Meta with component property
export default {
title: 'Button',
component: Button // <-- This is strictly necessary
}
// Example 2: Story with render method:
export const Primary = {
render: (args) => <Button {...args}>
}
```
2 - For typescript users, you need to be using Storybook 6.4 or higher.
CSF3 also brings a new function …
=> feat: support CSF3 format

example/src/internals.test.tsx, package.json, src/index.ts, yarn.lock
Issue: #7, #50
This PR adds an internal check to filter out non-story exports based on the includeStories/excludeStories parameters
This version adds support for the `includeStories` and `excludeStories` parameter to filter [non-story exports](https://storybook.js.org/docs/react/api/csf#non-story-exports) (#64)
=> feat: support exclude/include stories

README.md, example/src/__snapshots__/internals.test.tsx.snap, example/src/components/Button.stories.tsx, example/src/internals.test.tsx, src/index.ts, src/types.ts, src/utils.tsx
Issue: #49
The composedStory now contains the `storyName` property, which comes from:
- Story.storyName. If undefined, 
- Story.name (if using CSF1 or CSF2). If undefined,
- The exported key name from the stories module
Also added a recipe for automated testing, thanks a lot @synaptiko
=> feat: add storyName to composed story

example/.storybook/preview.tsx, example/setup.ts, package.json, src/types.ts
Issue: #61 
The globalconfig types now come from Storybook 6.4
=> fix: align global config types with Storybook 6.4

package.json, yarn.lock
Issue: this addon still references an RC version of SB
Fix to the latest minor version of SB (which is greater than the RC)
=> chore: update sb deps

example/src/__snapshots__/internals.test.tsx.snap, example/src/components/Button.stories.tsx, example/src/components/Button.test.tsx, src/index.ts
Issue: #30 
Fixed the following error when using the hooks function (ex. useArg) in the decorator function.
```
Error: Uncaught [Error: Storybook preview hooks can only be called inside decorators and story functions.]
```
=> fix: support addons that use hook api (#30)

package.json
Issue: Probably closes #99 
Add React18 to the peerDependency list
=> feat: add React18 to peerDeps

README.md, example/src/components/AccountForm.stories.tsx, src/index.ts
Issue: https://github.com/storybookjs/testing-react/issues/104
CSF3 allows for the render function to bubble up story to meta in the same way as args/parameters/etc, so this should be taken into account when composing stories.
=> Allow render function to be sourced from story meta

example/src/__snapshots__/internals.test.tsx.snap, example/src/components/Button.stories.tsx, example/src/internals.test.tsx
Issue: https://github.com/storybookjs/testing-react/issues/107
Just added a small test to document the conversion of csf3 `name` to `storyName`.
=> Add test for handling csf3 `name` -> `storyName`

.github/workflows/release.yml, package.json, yarn.lock
Preparing for the release of Storybook 7!
<details>
<summary>📦 Published PR as canary version: <code>1.3.1--canary.138.1078df7.0</code></summary>
<br />
```bash
npm install @storybook/testing-react@1.3.1--canary.138.1078df7.0
yarn add @storybook/testing-react@1.3.1--canary.138.1078df7.0
```
</details>
=> Support Storybook 7.0.0

package.json, yarn.lock
Issue: 
Bump @storybook/csf to 0.1.0
<details>
<summary>📦 Published PR as canary version: <code>1.3.1--canary.139.649899e.0</code></summary>
<br />
```bash
npm install @storybook/testing-react@1.3.1--canary.139.649899e.0
yarn add @storybook/testing-react@1.3.1--canary.139.649899e.0
```
</details>
=> Bump @storybook/csf to 0.1.0
